// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zWHcfnYS1J4jas7a22m02X0MU4t8mQw',
    appId: '1:1034318276501:web:9ffc19e4abb4710070789c',
    messagingSenderId: '1034318276501',
    projectId: 'calai-dd398',
    authDomain: 'calai-dd398.firebaseapp.com',
    databaseURL: 'https://calai-dd398-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calai-dd398.firebasestorage.app',
    measurementId: 'G-QFT2JCV9HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoiaN0wP8ocE0PkM5hzsOnOkPtPM9nhE',
    appId: '1:1034318276501:android:0c59aadf157b3f8f70789c',
    messagingSenderId: '1034318276501',
    projectId: 'calai-dd398',
    databaseURL: 'https://calai-dd398-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calai-dd398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGh-HdLGasWTfWDXW2xQsrGUn85WhqFnM',
    appId: '1:1034318276501:ios:dff19c3ce531520c70789c',
    messagingSenderId: '1034318276501',
    projectId: 'calai-dd398',
    databaseURL: 'https://calai-dd398-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calai-dd398.firebasestorage.app',
    iosClientId: '1034318276501-l63jh6duusjunefjlarj5n837uvptq0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.calai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGh-HdLGasWTfWDXW2xQsrGUn85WhqFnM',
    appId: '1:1034318276501:ios:dff19c3ce531520c70789c',
    messagingSenderId: '1034318276501',
    projectId: 'calai-dd398',
    databaseURL: 'https://calai-dd398-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calai-dd398.firebasestorage.app',
    iosClientId: '1034318276501-l63jh6duusjunefjlarj5n837uvptq0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.calai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6zWHcfnYS1J4jas7a22m02X0MU4t8mQw',
    appId: '1:1034318276501:web:89c627002f67db3b70789c',
    messagingSenderId: '1034318276501',
    projectId: 'calai-dd398',
    authDomain: 'calai-dd398.firebaseapp.com',
    databaseURL: 'https://calai-dd398-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calai-dd398.firebasestorage.app',
    measurementId: 'G-8Y977GX3NT',
  );
}
